# ============================================================================
# File: src/main/resources/application.yml
# Why: CORS/스트림 속도 설정 노출, 로깅 레벨은 운영에 맞춰 조정
# ============================================================================
server:
  port: 9000

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:8000,http://127.0.0.1:8000}
  stream:
    heartbeat-ms: ${STREAM_HEARTBEAT_MS:15000}
    delay-ms: ${STREAM_DELAY_MS:8}
  llm:
    provider: openai
    model: ${OPENAI_MODEL:gpt-4o-mini}
    base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
    api-key: ${OPENAI_API_KEY:}
    timeout-ms: 15000
  ratelimit:
    ip:
      capacity: ${RL_IP_CAPACITY:60}          # 분당 60회
      refillTokens: ${RL_IP_REFILL:60}
      refillPeriodSec: ${RL_IP_PERIOD:60}
    session:
      capacity: ${RL_SESS_CAPACITY:12}        # 10초당 12회
      refillTokens: ${RL_SESS_REFILL:12}
      refillPeriodSec: ${RL_SESS_PERIOD:10}

logging:
  level:
    com.example.embedchatbot: DEBUG
    org.springframework.web: INFO
