server:
  port: 9000

openai:
  api-key: ${OPENAI_API_KEY:}
  model: ${OPENAI_MODEL:gpt-4o-mini}
  base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
  temperature: 0.2
  max-tokens: 512
  connect-timeout-ms: 3000
  read-timeout-ms: 60000

stream:
  heartbeat-ms: ${STREAM_HEARTBEAT_MS:15000}

rag:
  enabled: true
  docs-path: data/docs
  top-k: 3

rl:
  ip:
    capacity: ${RL_IP_CAPACITY:60}
    refill:
      tokens: ${RL_IP_REFILL:60}
      periodSec: ${RL_IP_PERIOD:60}
  sess:
    capacity: ${RL_SESS_CAPACITY:12}
    refill:
      tokens: ${RL_SESS_REFILL:12}
      periodSec: ${RL_SESS_PERIOD:10}

logging:
  level:
    com.example.embedchatbot: INFO
    org.springframework.web: INFO
