name: E2E

on:
  workflow_dispatch:   # 수동 트리거

jobs:
  e2e:
    runs-on: ubuntu-latest
    if: ${{ secrets.OPENAI_API_KEY != '' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      # 백엔드 앱을 테스트 중에 직접 기동 (9000 포트)
      - name: Build app
        run: ./mvnw -B -q -DskipTests clean package

      - name: Run app in background
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
        run: |
          nohup java -jar target/*-SNAPSHOT.jar > app.log 2>&1 &
          # 포트 대기
          for i in {1..30}; do
            nc -z 127.0.0.1 9000 && break
            sleep 1
          done

      - name: Run E2E tests (-P e2e)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
        run: ./mvnw -B -q -P e2e verify

      - name: Show app logs on failure
        if: failure()
        run: |
          echo "==== app.log ===="
          tail -n 200 app.log || true
