name: E2E

# OpenAI 실계정을 사용한 엔드투엔드 검증 파이프라인.
# 조건: secrets.OPENAI_API_KEY가 설정된 경우에만 실행하며, 수동 트리거(workflow_dispatch)로 운영자가 필요 시 수행.
# 타임아웃: GitHub Actions 기본 6시간이지만, app 기동/테스트를 15분 이내로 마치는 것을 목표.

on:
  workflow_dispatch:   # 수동 트리거

jobs:
  e2e:
    runs-on: ubuntu-latest
    if: ${{ secrets.OPENAI_API_KEY != '' }}

    # E2E는 실제 OpenAI 호출을 수행하므로 테스트 병렬성 대신 직렬 실행을 택한다.
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      # 백엔드 앱을 테스트 중에 직접 기동 (9000 포트)
      - name: Build app
        run: ./mvnw -B -q -DskipTests clean package

      - name: Run app in background
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
        run: |
          nohup java -jar target/*-SNAPSHOT.jar > app.log 2>&1 &
          # 포트 대기
          for i in {1..30}; do
            nc -z 127.0.0.1 9000 && break
            sleep 1
          done

      - name: Run E2E tests (-P e2e)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
        run: ./mvnw -B -q -P e2e verify

      # 실패 시 앱 로그를 아티팩트 대신 콘솔로 출력하여 디버깅 시간을 단축
      - name: Show app logs on failure
        if: failure()
        run: |
          echo "==== app.log ===="
          tail -n 200 app.log || true
